export const chapters = [
  { id:'intro', name:'Begynnelsen', duration:14, kicker:'ET USYNLIG SAMARBEID', title:'Et lite signal.<br>Et sted på jorden.', body:'Du kjører på en liten vei. Høyt over deg sender satellitter ut et stille svar på et stort spørsmål: <strong>Hvor er jeg, egentlig?</strong>', detail:'Bilen sender ingenting til GPS-satellittene. Den bare lytter. La oss følge signalet hele veien.', label:'FRA VERDENSROMMET TIL DEG', note:'En liten reise i noe vi tar for gitt.' },
  { id:'circle1', name:'Én satellitt · en sirkel', duration:15, kicker:'VI BEGYNNER PÅ ET ARK', title:'Et sted langs<br>den blå streken.', body:'Signalet forteller når det ble sendt. Reisetiden ganger lysets hastighet gir en avstand. <strong>Alle punktene på sirkelen er like langt unna.</strong>', detail:'Først leker vi i 2D, med en klokke som går helt riktig. Den fargede flaten hjelper oss å se formen; bare kanten er en mulig posisjon.', label:'2D · ÉN AVSTAND', note:'Vi måler tid. Og tegner avstand.' },
  { id:'circle2', name:'To satellitter · to svar', duration:17, kicker:'EN NY BIT AV PUSLESPILLET', title:'To streker.<br>To muligheter.', body:'En ny satellitt gir en ny sirkel. Du må være på <strong>begge sirklene samtidig.</strong> Se hvordan mulighetene krymper til to små skjæringspunkter.', detail:'Det er avstander vi måler, ikke vinkler. Prinsippet heter trilaterasjon.', label:'2D · TO AVSTANDER', note:'To muligheter. Men bare én bil.' },
  { id:'circle3', name:'Tre satellitter · ett sted', duration:17, kicker:'NÅ FALLER DET PÅ PLASS', title:'Der strekene<br>møtes, er du.', body:'Den tredje sirkelen går gjennom ett av de to punktene. Det andre ligger feil i forhold til den nye satellitten og <strong>kan forkastes.</strong>', detail:'Med kjent klokke finner denne 2D-modellen x og y. En virkelig mottaker må også finne sin egen klokkefeil.', label:'2D · TRE AVSTANDER', note:'Alle avstandene må stemme samtidig.' },
  { id:'circle4', name:'Fire satellitter · klokken', duration:18, kicker:'DEN LILLE FEILEN SOM BETYR MYE', title:'Og hvis klokken<br>din går feil?', body:'Da blir alle de målte avstandene forskjøvet. Mottakeren justerer posisjon og <strong>én felles klokkefeil</strong> til målingene passer best sammen.', detail:'I 2D er det tre ukjente: x, y og tid. Den fjerde målingen gir ekstra kontroll. Bare 1 mikrosekund tilsvarer omtrent 300 meter.', label:'2D · AVSTAND + KLOKKEFEIL', note:'Samme tidsfeil. Et tillegg i alle avstander.' },
  { id:'sphere1', name:'3D · en kuleflate', duration:15, kicker:'LA OSS LØFTE ARKET', title:'En sirkel får<br>en dimensjon til.', body:'Ute i verden finnes også høyde. Én kjent avstand blir nå en <strong>kuleflate</strong> rundt satellitten. Du kan være hvor som helst på den.', detail:'Vi holder klokken riktig igjen mens vi ser på geometrien. Kulene er avstandsflater, ikke satellittenes signaldekning.', label:'3D · ÉN KULEFLATE', note:'Samme tanke. Bare med plass til høyde.' },
  { id:'sphere2', name:'3D · en skjæringssirkel', duration:18, kicker:'SE DER FARGENE MØTES', title:'To kuleflater.<br>Én sirkel.', body:'Den nye kulen vokser rolig frem. Akkurat der de to overflatene skjærer hverandre, ligger <strong>en lysende sirkel</strong> av mulige posisjoner.', detail:'Det fargede overlappende volumet er ikke svaret. Bare skjæringslinjen har riktig avstand til begge satellittene.', label:'3D · SKJÆRINGEN ER EN SIRKEL', note:'Vi leter på overflatene, ikke inni kulene.' },
  { id:'sphere3', name:'3D · to mulige punkter', duration:23, kicker:'FRA EN LINJE TIL TO STEDER', title:'Nesten fremme.<br>Men hvilket punkt?', body:'Den tredje kuleflaten møter skjæringssirkelen i to punkter. Så legger vi inn et lite stykke jord: <strong>ett punkt passer med en bil på bakken.</strong>', detail:'Det andre ligger langt over bakken i modellen. Kjent, rimelig høyde kan forkaste det. Uten slik tilleggsinformasjon må vi beholde begge.', label:'3D · TO KANDIDATER', note:'Jorden gir oss en ekstra opplysning.' },
  { id:'sphere4', name:'3D · fire ukjente', duration:23, kicker:'SLIK GJØR EN VANLIG GPS DET', title:'Tre koordinater.<br>Og én klokke.', body:'En vanlig mottaker kjenner ikke sin egen tidsfeil. Fire satellitter gir fire ligninger for <strong>x, y, z og klokkefeilen b.</strong> Kuleflatene justeres til én felles løsning.', detail:'Dette er pseudoavstander: sann avstand + c·b, etter satellittens klokkekorreksjon. Flere gode signaler gir bedre kontroll på løsningen.', label:'3D · FIRE MÅLINGER, FIRE UKJENTE', note:'Posisjonen og tiden finner vi sammen.' },
  { id:'control', name:'Hvem følger satellitten?', duration:27, kicker:'BAK HVER PRIKK PÅ HIMMELEN', title:'Men hvem forteller<br>satellitten hvor den er?', body:'Bakkestasjoner lytter til satellittsignalene. Et kontrollsenter beregner bane og klokkefeil, og laster opp nye <strong>efemerider</strong> – en oppskrift på satellittens posisjon over tid.', detail:'Små avvik gir nye beregninger. Ved behov endres selve banen med en manøver. Satellitten videresender banedataene; mottakeren regner ut hvor den var da signalet gikk.', label:'ROMMET ↔ KONTROLLSEGMENTET', note:'Måle. Beregne. Laste opp. Følge med.' },
  { id:'relativity', name:'En liten takk til Einstein', duration:20, kicker:'TIDEN ER IKKE HELT DEN SAMME', title:'Selv klokkene<br>har en reise.', body:'Høyt over jorden får svakere tyngdekraft satellittklokkene til å gå raskere. Bevegelsen får dem til å gå langsommere. <strong>Tyngdekrafteffekten vinner.</strong>', detail:'GPS korrigerer for begge relativistiske effekter. Ellers ville tidsfeilen vokse og avstandsmålingene bli stadig mer feil.', label:'PRESIS TID ER PRESIS AVSTAND', note:'Litt Einstein, hver gang du finner frem.' },
  { id:'velocity', name:'Fra posisjon til fart', duration:24, kicker:'BILEN RULLER VIDERE', title:'Vi vet hvor.<br>Men hvor fort?', body:'To posisjoner og tiden mellom dem gir en gjennomsnittshastighet. Når bilen stanser, fryser vi den <strong>akkurat der den er</strong> og tegner avstandsgeometrien til alle satellittene.', detail:'Posisjonsstøy kan gjøre dette fartsanslaget urolig. GPS kan også måle bevegelse direkte i signalets frekvens.', label:'POSISJON OVER TID', note:'En vei. To tidspunkt. En bevegelse.' },
  { id:'doppler', name:'Fart i selve signalet', duration:28, kicker:'DU KJENNER DET FRA EN SIRENE', title:'Bevegelsen setter<br>spor i bølgene.', body:'Når avstanden avtar, øker den mottatte frekvensen. Når avstanden øker, faller den. <strong>Doppler måler farten langs hver siktelinje.</strong>', detail:'Mottakeren tar hensyn til satellittenes egen bevegelse. Flere siktelinjer gir bilens hastighetsvektor og mottakerens klokkedrift. Fart er lengden av vektoren.', label:'DOPPLER · FLERE RETNINGER, ÉN FART', note:'Én satellitt ser bare sin del av bevegelsen.' },
  { id:'error', name:'Når strekene ikke møtes', duration:23, kicker:'VIRKELIGHETEN TEGNER LITT SKJEVT', title:'Et lite sprik.<br>En feiltrekant.', body:'Støy og forsinkelser gjør at sirklene ikke møtes helt. De parvise skjæringene danner her en liten <strong>feiltrekant.</strong> Mottakeren finner posisjonen som samlet passer målingene best.', detail:'Dette er en skisse av minste kvadraters metode, ikke en garanti for at bilen ligger i trekanten. Satellitter i flere retninger gir gunstigere geometri.', label:'MÅLEFEIL + GEOMETRI = USIKKERHET', note:'Et ærlig anslag er bedre enn falsk presisjon.' },
  { id:'echo', name:'Glassbyen & spøkelsesbilen', duration:30, kicker:'NÅ TAR SIGNALET EN OMVEI', title:'Du er her.<br>GPS-en tror du er der.', body:'Bilen kjører bak en bygning. Det direkte signalet blokkeres, men et ekko fra glassfasaden kommer frem. Den lengre veien ser ut som <strong>en større avstand.</strong>', detail:'Refleksjoner kan forskyve løsningen til en spøkelsesposisjon i nabogaten. Når fri sikt kommer tilbake, kan mottakeren igjen stole mer på de direkte signalene.', label:'BYROM · REFLEKSJON OG BLOKKERING', note:'Et ekko bærer riktig beskjed. Bare for sent.' },
  { id:'jam', name:'Når signalet drukner', duration:20, kicker:'ET SVAKT SIGNAL I EN STØYENDE VERDEN', title:'Noen ganger<br>blir det stille.', body:'GPS-signalene er svake når de når bakken. Kraftig radiostøy kan overdøve dem, slik at mottakeren <strong>mister satellittene og posisjonen.</strong> Dette kalles jamming.', detail:'Skjerming, tunneler og dårlig sikt kan også gi signaltap. Jamming blokkerer; spoofing er noe annet – falske signaler som forsøker å lure mottakeren.', label:'SIGNAL TIL STEDE ≠ SIGNAL SOM KAN LESES', note:'Uten pålitelige signaler må vi si: ukjent.' },
  { id:'outro', name:'Og der er du.', duration:13, kicker:'NESTE GANG DU SER DEN LILLE PRIKKEN', title:'En hel verden.<br>For å finne deg.', body:'Geometri gjør tid til et sted. Bølgene avslører farten. Bakkestasjoner og presise klokker holder det hele sammen. <strong>Og du kan fortsette turen.</strong>', detail:'Spill fortellingen på nytt, eller velg et kapittel for å se nærmere på en av ideene.', label:'GEOMETRI · TID · BEVEGELSE', note:'God tur videre.' }
];
let offset = 0;
for (const chapter of chapters) { chapter.start = offset; offset += chapter.duration; }
export const duration = offset;
export function chapterAt(time) { return chapters.findLast(c => time >= c.start) || chapters[0]; }
